### ISSUE TITLE
Is it possible to create new VPS via api?

### ISSUE THREAD

**Issue by BouzayenMohamed** [ovh/node-ovh#47] opened 2023-05-17 20:52 UTC
I need to automate the process of creating new VPS, and the docs was not helpful.

**Comment by deathiop** [comment] 2023-05-29 14:41
As the problem is not related to the `node-ovh` wrapper, I will close this issue, and let you send your issue to our customer mailing-list, api@ml.ovh.net. You can subscribe by sending an email to api-subscribe@ml.ovh.net.

**Closed by deathiop** 2023-05-29 14:41 UTC
