### ISSUE TITLE
validationUrl issue

### ISSUE THREAD

**Issue by tiofabby** [ovh/node-ovh#39] opened 2019-11-21 20:39 UTC
Hi,
I am starting using node-ovh and put following code:

```
var ovh = require('ovh')({
  endpoint:     'ovh-eu',
  appKey:       '_removed_',
  appSecret:    '_removed_',
})

ovh.request('POST', '/auth/credential', {
    'accessRules': [
      { 'method': 'GET', 'path': '/*'},
      { 'method': 'POST', 'path': '/*'},
      { 'method': 'PUT', 'path': '/*'},
      { 'method': 'DELETE', 'path': '/*'}
    ]
  }, function (error, credential) {
    console.log('OVH: ', error || credential)
  })

```
This gives me:

```
{ validationUrl:
   'https://eu.api.ovh.com/auth/?credentialToken=_removed_',
  consumerKey: '_removed_',
  state: 'pendingValidation' }

```
So I go to such validationUrl, but this gives me the following error page

![image](https://user-images.githubusercontent.com/9844354/69374606-ab85d280-0ca6-11ea-9698-9d0c770b37ca.png)

I am doing something wrong?
I tried to reach same url but with my OVH account already logged in another tab (session opened) but issue is then.

I hope you guys can help.
Thank you
Fabrice

**Comment by rbeuque74** [comment] 2019-11-22 19:57
Hello @tiofabby;
Thanks for raising an issue.
It seems that your code is correct (from what I see). Can you test if you can still reproduce this bug ?
If yes, can you bring this to the API mailing-list (https://github.com/ovh/node-ovh/blob/master/README.md#ovh-europe Community support) because this problem is probably not linked to node-ovh.

Thanks,
Romain

**Comment by tiofabby** [comment] 2019-11-22 23:51
Okay Thank you Romain, I have reached out to such mailing list then.
Thanks
Fabrice

**Comment by julieni** [comment] 2019-11-23 09:51
On the screenshot posted on the mailing list, the URL the browser is pointing to ends with %27, an URL-encoded single quote.
My guess is that @tiofabby did copy/paste that extra char by mistake in the browser.

**Comment by rbeuque74** [comment] 2019-11-23 12:04
Indeed, confirming that.
Also tested the snippet on my laptop, copying the link without the final single quote is working.

Thanks all, closing this issue :)
Romain

**Closed by rbeuque74** 2019-11-23 12:04 UTC

**Comment by tiofabby** [comment] 2019-11-24 13:27
Hi, the link generated I clicked on does not contain the %27, extra characters. I believe these get added when being redirected to landing page. So such issue should be kept opened so this can be fixed.
Workaround for now will be to remove these extra characters manually indeed.
Thanks
Fabrice

**Comment by julieni** [comment] 2019-11-24 14:22
@tiofabby: %27 is an URL encoded single quote: `'`
When you click on the link from your terminal, I guess this one captures the `'` at the end, for exemple your JSON snippet:
```
{
  validationUrl: 'https://eu.api.ovh.com/auth/?credentialToken=_removed_',
  consumerKey: '_removed_',
  state: 'pendingValidation' 
}
```

The URL opened by your browser is:
`https://eu.api.ovh.com/auth/?credentialToken=_removed_'`
instead of (note the last char which is the single quote)
`https://eu.api.ovh.com/auth/?credentialToken=_removed_`

So there's really no issue here

**Comment by tiofabby** [comment] 2019-11-24 17:01
Yes you are right Julien, Thank you
